version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: persona_db
    volumes:
      - mongo_data:/data/db
      - ./scripts/persona_ddl_mongo.js:/docker-entrypoint-initdb.d/01_persona_ddl_mongo.js
      - ./scripts/persona_dml_mongo.js:/docker-entrypoint-initdb.d/02_persona_dml_mongo.js
    ports:
      - "27017:27017"
    command: mongod --auth

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  mariadb:
    image: mariadb:10.3.10
    container_name: mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: persona_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - maria_data:/var/lib/mysql
      - ./scripts/persona_ddl_maria.sql:/docker-entrypoint-initdb.d/01_persona_ddl_maria.sql
      - ./scripts/persona_dml_maria.sql:/docker-entrypoint-initdb.d/02_persona_dml_maria.sql
    restart: always

  personapp-cli-service:
    image: personapp-cli-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personapp-cli-service
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - APP_TYPE=cli
    depends_on:
      - mariadb
      - mongo
    stdin_open: true
    tty: true

  personapp-rest-service:
    image: personapp-rest-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personapp-rest-service
    ports:
      - "3000:3000"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - APP_TYPE=rest
    depends_on:
      - mariadb
      - mongo

volumes:
  mongo_data:
  maria_data:

